name: Scrape ING Bearbeitungszeiten
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 * * * *' # every twenty minutes

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    outputs:
      bearbeitungszeiten_date: ${{ steps.parse.outputs.ing_date }}
      bearbeitungszeiten_values: ${{ steps.parse.outputs.ing_values }}

    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
              
    - name: Setup htmlq
      uses: remarkablemark/setup-htmlq@v2

    - name: Curl
      id: curl
      run: |-
        response=$(curl -s 'https://www.ing.de/partner/news/')
        echo "response=\"$response\"" >> $GITHUB_OUTPUT
    
    - name: Parse Bearbeitungszeiten
      id: parse
      run: |-
        echo "ing_date=$(echo ${{ steps.curl.outputs.response }} | htmlq --text '#Bearbeitungszeiten .rich-content__subheadline' | awk -F' +' '{print $2}')" >> $GITHUB_OUTPUT
        echo "ing_values=$(echo ${{ steps.curl.outputs.response }} | htmlq --text '#Bearbeitungszeiten table td:nth-child(3)' | awk 1 ORS=';')" >> $GITHUB_OUTPUT

    - name: Store CSV
      run: echo "${{ steps.parse.outputs.ing_date }};${{ steps.parse.outputs.ing_values }}" > ing_bearbeitungszeiten.csv

    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
