name: Scrape ING partner news
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0,20,40 * * * *' # every twenty minutes
permissions:
  contents: write
jobs:
  scrape_ing:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
              
    - name: Setup htmlq
      uses: remarkablemark/setup-htmlq@v2
    
    - name: Get Stand
      run: echo "ING_STAND=$(curl --silent 'https://www.ing.de/partner/news/' | htmlq --text '#Bearbeitungszeiten .rich-content__subheadline' | awk -F' +' '{print $2}'") >> $GITHUB_ENV

    - name: Get Bearbeitungszeiten
      run: echo "ING_VALUES=$(curl --silent 'https://www.ing.de/partner/news/' | htmlq --text '#Bearbeitungszeiten table td:nth-child(3)' | awk 1 ORS=';'") >> $GITHUB_ENV

    - name: Store CSV
      run: echo "${{ env.ING_STAND }};${{ env.ING_VALUES }}" > ing_bearbeitungszeiten.csv


    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
