name: Scrape ING Bearbeitungszeiten
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 * * * *' # every hour

permissions:
  contents: write

defaults:
  run:
    working-directory: a/b/c

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      CSV_FILE: ing_bearbeitungszeiten.csv
    outputs:
      bearbeitungszeiten_date: ${{ steps.parse.outputs.ing_date }}
      bearbeitungszeiten_values: ${{ steps.parse.outputs.ing_values }}

    steps:
      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Setup htmlq
        uses: remarkablemark/setup-htmlq@v2

      - name: Curl and Parse Bearbeitungszeiten
        id: parse
        run: |-
          RESPONSE=$(curl --silent https://www.ing.de/partner/news/)
          ING_DATE=$(echo "$RESPONSE" | htmlq --text '#Bearbeitungszeiten .rich-content__subheadline' | awk -F' +' '{print $2}') 
          ING_VALUES=$(echo "$RESPONSE" | htmlq --text '#Bearbeitungszeiten table td:nth-child(3)' | awk 1 ORS=';')
          echo "ing_date=$ING_DATE" >> $GITHUB_OUTPUT
          echo "ing_values=$ING_VALUES" >> $GITHUB_OUTPUT

      #     The grep utility exits with one of the following values:
      #
      #     0     One or more lines were selected.
      #     1     No lines were selected.
      #     >1    An error occurred.
      - name: Compare Values
        id: compare
        run: |-
          grep "${{ steps.parse.outputs.ing_values }}" $CSV_FILE
          echo $?

      - name: Store CSV
        id: store
        run: |-
          if grep -q "${{ steps.parse.outputs.ing_values }}" "$CSV_FILE"; then
          echo "Found!"
          else
          echo "Not Found!"
          echo "${{ steps.parse.outputs.ing_date }};${{ steps.parse.outputs.ing_values }}" > $CSV_FILE
          fi

      - name: Commit and push if the data has changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "ING: Update Bearbeitungszeiten vom ${{ steps.parse.outputs.ing_date }}" || exit 0
          git push
