name: Scrape ING parter news
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0,20,40 * * * *' # every twenty minutes
permissions:
  contents: write
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
      
    - name: Fetch latest data
      run: |-
        curl -s "https://www.ing.de/partner/news/" > news.html
        
    - name: Setup htmlq
      uses: remarkablemark/setup-htmlq@v2
    
    - name: Print version
      run: htmlq --version

    - name: Print help
      run: htmlq --help

    - name: Get Stand
      run: curl --silent "https://www.ing.de/partner/news/" | htmlq --text '#Bearbeitungszeiten .rich-content__subheadline' > stand.csv

    - name: Get Bearbeitungszeiten
      run: curl --silent "https://www.ing.de/partner/news/" | htmlq --text '#Bearbeitungszeiten table td' > values.csv

    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
